[project]
name = "nichelibrary"
version = "1.1.7"
description = "C++ library for competitive programming"
readme = "README.md"
requires-python = ">=3.13"
dependencies = []

[dependency-groups]
dev = [
    "competitive-verifier",
    "mypy>=2.3.0",
    "pyright>=1.1.411",
    "ruff>=0.15.12",
]

[tool.mypy]
python_version = "3.13"

[tool.pyright]
pythonVersion = "3.13"

[tool.ruff.format]
quote-style = "preserve"

[tool.ruff.lint]
extend-select = ["I"]

[tool.uv.sources]
competitive-verifier = { git = "https://github.com/NotLeonian/competitive-verifier", rev = "604d80fd40d7ed5474c8ac60674a086de2cce531" }
